#!/bin/sh

##########################################################################################
#  __  o  __   __   __  |__   __                                                         #
# |__) | |  ' (__( |  ) |  ) (__(                                                        # 
# |                                                                                      #
#                                                                                        #
# File: brew_piranha.sh                                                                  #
  VERSION="v1.0.3"                                                                       #
# Author: Justin C. Bagley                                                               #
# Date: Created by Justin Bagley on Thu, Apr 16 23:10:44 CDT 2020.                       #
# Last update: December 7, 2020                                                          #
# Copyright (c) 2020 Justin C. Bagley. All rights reserved.                              #
# Please report bugs to <bagleyj@umsl.edu>.                                              #
#                                                                                        #
# Description:                                                                           #
# THIS SCRIPT INSTALLS AND SETS UP HOMEBREW PIrANHA, AS OPPOSED TO LOCAL VERSION (IF     #
# ACCIDENTALLY RUN ON LINUX, ATTEMPTS LOCAL INSTALL/SETUP OF GitHub PIrANHA-MASTER)      #
#                                                                                        #
##########################################################################################

brew_piranha () {

######################################## START ###########################################
##########################################################################################
echo "INFO      | $(date) |----------------------------------------------------------------"
echo "INFO      | $(date) | brew_piranha, v1.0.3 December 2020                             "
echo "INFO      | $(date) | Copyright (c) 2020 Justin C. Bagley. All rights reserved.      "
echo "INFO      | $(date) |----------------------------------------------------------------"

######################################## START ###########################################
echo "INFO      | $(date) | Initiating Homebrew PIrANHA install/setup procedures... "

		####### CHECK MACHINE TYPE:
		## This idea and code came from the following URL (Lines 87-95 code is reused here):
		## https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux
		echo "INFO      | $(date) | Checking machine type... "
		unameOut="$(uname -s)";
		case "${unameOut}" in
			Linux*)     machine=Linux;;
			Darwin*)    machine=Mac;;
			CYGWIN*)    machine=Cygwin;;
			MINGW*)     machine=MinGw;;
			*)          machine="UNKNOWN:${unameOut}"
		esac;

		echo "INFO      | $(date) | Done. "

		####### CHECK FOR HOMEBREW, ATTEMPT INSTALL (ON MAC) OR EXIT IF UNWANTED / NOT FOUND:
		echo "INFO      | $(date) | Checking for Homebrew (https://brew.sh)... "
		MY_HB_CHECK="$(which brew 2> /dev/null | wc -l | sed 's/\ //g')";
		##
		if [[ "$machine" = "Mac" ]] && [[ "$MY_HB_CHECK" = "0" ]]; then
			echo "WARNING   | $(date) | No Homebrew install detected! "
			echo "INFO      | $(date) | Attempting to install Homebrew locally... "
			## Download Homebrew installer script:
			echo "INFO      | $(date) | Downloading Homebrew installer script and installing... "
			echo "INFO      | $(date) | NOTE: You may need to re-run this brew_piranha installer after the Homebrew install is complete. "
			/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)";
		elif [[ "$machine" != "Mac" ]] && [[ "$MY_HB_CHECK" = "0" ]]; then
			echo "WARNING   | $(date) | No Homebrew install detected! "
			echo "WARNING   | $(date) | Cannot install Homebrew on ${machine} machine... "
#			echo "INFO      | $(date) | Quitting... "
#			exit 1;	
		fi
		##

		echo "INFO      | $(date) | Done. "
		
		####### INSTALL/UPGRADE HOMEBREW PIrANHA:
		##
		if [[ "$machine" = "Mac" ]]; then

			## First check to see if there is a Homebrew alias in ~/.bash_profile (indicating
			## a prior local Homebrew piranha install is present):
			MY_HB_PIRANHA_ALIAS_CHECK="$(cat ~/.bash_profile | grep '### HOMEBREW PIrANHA ALIAS:' | wc -l | sed 's/\ //g')";
			
			##
			if [[ "$MY_HB_PIRANHA_ALIAS_CHECK" = "0" ]]; then
			 
				## Case #1: Prior Homebrew install absent.
				## If no prior Homebrew piranha install, do the install:
						
				echo "INFO      | $(date) | Installing latest Homebrew PIrANHA version on ${USER}'s ${machine}... "
				brew update ;
				brew update ; 
				brew upgrade --fetch-HEAD piranha ; 
				brew info piranha ;
				MY_PIRANHA_CELLAR="$(brew info piranha | grep -h 'Cellar' | sed 's/\ (.*//g')";
				MY_BREW_PIRANHA_VERSION="$(brew info piranha | grep -h 'Cellar' | sed 's/\ (.*//g; s/.*\///g')";
				echo "INFO      | $(date) | Homebrew PIrANHA version: $MY_BREW_PIRANHA_VERSION "
				echo "INFO      | $(date) | Homebrew PIrANHA location: $MY_PIRANHA_CELLAR "

				####### ADD BASH PROFILE PIrANHA ALIAS:
				echo "INFO      | $(date) | Adding Homebrew PIrANHA alias to ~/.bash_profile... "
				MY_BREW_PIRANHA_MAIN="$(echo "$MY_PIRANHA_CELLAR"/piranha)"
				echo "#################### HOMEBREW PIrANHA ALIAS:" >> ~/.bash_profile ;
				echo "alias piranha=\""$MY_BREW_PIRANHA_MAIN"\"" >> ~/.bash_profile ;
				echo "source \""$MY_PIRANHA_CELLAR"/completions/init.sh\"" >> ~/.bash_profile ;
				source ~/.bash_profile ;

				####### REMOVE ~/bin/piranha, IF PRESENT (TO AVOID CONFLICT):
				if [[ -s ~/bin/piranha ]]; then
					rm ~/bin/piranha 
				fi
		
				echo "INFO      | $(date) | Done. "

			elif [[ "$MY_HB_PIRANHA_ALIAS_CHECK" = "1" ]] || [[ "$MY_HB_PIRANHA_ALIAS_CHECK" -gt "0" ]]; then

				## Case #2: Prior Homebrew install exists.
				## If existing prior install found:
				
				## First, remove ~/.bash_profile alias:
				sed -i '' -e '/\#\#\ HOMEBREW\ PIrANHA\ ALIAS\:/,+1d' ~/.bash_profile ;
				sed -i '' '/piranha\/.*\/completions\/init\.sh/d' ~/.bash_profile ;
				
				## Next, redo test then do fresh Homebrew piranha install:	
				MY_HB_PIRANHA_ALIAS_CHECK="$(cat ~/.bash_profile | grep '### HOMEBREW PIrANHA ALIAS:' | wc -l | sed 's/\ //g')";
				if [[ "$MY_HB_PIRANHA_ALIAS_CHECK" = "0" ]]; then
					echo "INFO      | $(date) | Installing latest Homebrew PIrANHA version on ${USER}'s ${machine}... "
					brew update ;
					brew update ; 
					brew upgrade --fetch-HEAD piranha ; 
					brew info piranha ;
					MY_PIRANHA_CELLAR="$(brew info piranha | grep -h 'Cellar' | sed 's/\ (.*//g')";
					MY_BREW_PIRANHA_VERSION="$(brew info piranha | grep -h 'Cellar' | sed 's/\ (.*//g; s/.*\///g')";
					echo "INFO      | $(date) | Homebrew PIrANHA version: $MY_BREW_PIRANHA_VERSION "
					echo "INFO      | $(date) | Homebrew PIrANHA location: $MY_PIRANHA_CELLAR "
			
					####### ADD BASH PROFILE PIrANHA ALIAS:
					echo "INFO      | $(date) | Adding Homebrew PIrANHA alias to ~/.bash_profile... "
					MY_BREW_PIRANHA_MAIN="$(echo "$MY_PIRANHA_CELLAR"/piranha)"
					echo "#################### HOMEBREW PIrANHA ALIAS:" >> ~/.bash_profile ;
					echo "alias piranha=\""$MY_BREW_PIRANHA_MAIN"\"" >> ~/.bash_profile ;
					echo "source \""$MY_PIRANHA_CELLAR"/completions/init.sh\"" >> ~/.bash_profile ;
					source ~/.bash_profile ;
	
					####### REMOVE ~/bin/piranha, IF PRESENT (TO AVOID CONFLICT):
					if [[ -s ~/bin/piranha ]]; then
						rm ~/bin/piranha 
					fi
		
					echo "INFO      | $(date) | Done. "
				fi
			
			fi
			##

        else

			echo "WARNING   | $(date) | Cannot install PIrANHA on ${machine} with Homebrew. "

#			echo "INFO      | $(date) | Checking for PIrANHA alias and adding if not present (assuming piranha-master/ already exists)... "
#			####### ADD BASH PROFILE PIrANHA ALIAS:
#			MY_PIRANHA_ALIAS_CHECK1="$(grep -h 'PIrANHA\ ALIAS\:' ~/.bash_profile | wc -l | sed 's/\ //g')"; 
#			MY_PIRANHA_ALIAS_CHECK2="$(grep -h 'PIrANHA\ ALIAS\:' ~/.bashrc | wc -l | sed 's/\ //g')"; 
#				if [[ "$MY_PIRANHA_ALIAS_CHECK1" = "0" ]] && [[ "$MY_PIRANHA_ALIAS_CHECK2" = "0" ]]; then
#					echo "INFO      | $(date) | Adding PIrANHA alias to ~/.bashrc... "
#					echo "#################### HOMEBREW PIrANHA ALIAS:" >> ~/.bashrc ;
#					echo "alias piranha=\"\~\/local\/opt\/piranha\/piranha\"" >> ~/.bashrc ;
#					source ~/.bashrc ;
#				fi

			## On Linux, do local_piranha setup, assuming piranha-master/ already exists in expected location 
			## (~/local/opt/piranha-master/):
			echo "INFO      | $(date) | Doing local PIrANHA setup for Linux... "
			if [[ -s ./local_piranha ]]; then
				chmod u+x ./local_piranha ; 
				. source local_piranha ;			
			else
				echo "ERROR     | $(date) | Quitting... "
				exit 1 ;
			fi
        fi
		##
		
echo "INFO      | $(date) | Done. 
"
##########################################################################################
######################################### END ############################################

}

brew_piranha

exit 0

