#!/bin/sh

##########################################################################################
#  __  o  __   __   __  |__   __                                                         #
# |__) | |  ' (__( |  ) |  ) (__(                                                        # 
# |                                                                                      #
#                                                                                        #
# File: local_piranha (install_piranha.sh)                                               #
  VERSION="v1.0.2"                                                                       #
# Author: Justin C. Bagley                                                               #
# Date: Created by Justin Bagley on Thu, Apr 16 23:10:44 CDT 2020.                       #
# Last update: December 7, 2020                                                          #
# Copyright (c) 2020 Justin C. Bagley. All rights reserved.                              #
# Please report bugs to <bagleyj@umsl.edu>.                                              #
#                                                                                        #
# Description:                                                                           #
# THIS SCRIPT SETS UP LOCAL PIrANHA, AS OPPOSED TO THE VERSION AVAILBLE THROUGH HOMEBREW #
#                                                                                        #
##########################################################################################

local_piranha () {

######################################## START ###########################################
##########################################################################################
echo "INFO      | $(date) |----------------------------------------------------------------"
echo "INFO      | $(date) | local_piranha, v1.0.2 December 2020                            "
echo "INFO      | $(date) | Copyright (c) 2020 Justin C. Bagley. All rights reserved.      "
echo "INFO      | $(date) |----------------------------------------------------------------"

######################################## START ###########################################
echo "INFO      | $(date) | Initiating local PIrANHA install/setup procedures... "

		####### CHECK MACHINE TYPE:
		## This idea and code came from the following URL (Lines 87-95 code is reused here):
		## https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux
		echo "INFO      | $(date) | Checking machine type... "
		unameOut="$(uname -s)";
		case "${unameOut}" in
			Linux*)     machine=Linux;;
			Darwin*)    machine=Mac;;
			CYGWIN*)    machine=Cygwin;;
			MINGW*)     machine=MinGw;;
			*)          machine="UNKNOWN:${unameOut}"
		esac;
		echo "INFO      | $(date) | Found machine type ${machine}. "

		echo "INFO      | $(date) | Done. "

        ####### REMOVE HOMEBREW PIRANHA ALIAS IN ~/.bash_profile (or ~/.bashrc on Linux), 
        ####### IF PRESENT:
		if [[ "$machine" = "Mac" ]]; then
			MY_PIRANHA_ALIAS_CHECK="$(grep -h '\#\#\#\#\ HOMEBREW\ PIrANHA\ ALIAS\:' ~/.bash_profile | wc -l | sed 's/\ //g')"; 
				if [[ "$MY_PIRANHA_ALIAS_CHECK" != "0" ]]; then
					sed -i '' '/\ HOMEBREW\ PIrANHA\ ALIAS/d' ~/.bash_profile  ;
					sed -i '' '/alias\ piranha\=.*\/Cellar/d' ~/.bash_profile  ;
					sed -i '' '/piranha\/.*\/completions\/init\.sh/d' ~/.bash_profile ;
				fi
		elif [[ "$machine" = "Linux" ]]; then
			MY_PIRANHA_ALIAS_CHECK1="$(grep -h 'PIrANHA\ ALIAS\:' ~/.bash_profile | wc -l | sed 's/\ //g')"; 
			MY_PIRANHA_ALIAS_CHECK2="$(grep -h 'PIrANHA\ ALIAS\:' ~/.bashrc | wc -l | sed 's/\ //g')"; 
				if [[ "$MY_PIRANHA_ALIAS_CHECK1" != "0" ]] || [[ "$MY_PIRANHA_ALIAS_CHECK2" != "0" ]]; then
					sed -i '/PIrANHA\ ALIAS/d' ~/.bash_profile  ;
					sed -i '/alias\ piranha\=/d' ~/.bash_profile  ;
					sed -i '/piranha\/.*\/completions\/init\.sh/d' ~/.bash_profile ;
					sed -i '/PIrANHA\ ALIAS/d' ~/.bashrc  ;
					sed -i '/alias\ piranha\=/d' ~/.bashrc  ;
					sed -i '/piranha\/.*\/completions\/init\.sh/d' ~/.bashrc ;
				fi
		fi

		
		####### CUSTOM INSTALL / SET UP FOR PIrANHA 
		## The operations are different if the current machine is one of the author's machines/accounts, 
		## versus if local_piranha install and setup are being tried on a user machine/account. On
		## author machine, no need to install. On user machine, may need to do fresh install.
		
        ###
        if [[ "$USER" = "justinbagley" ]] || [[ "$USER" = "jcbagley" ]] || [[ "$USER" = "bagle004" ]]; then

	        ## CASE #1: AUTHOR MACHINE
			
			## SET UP PIrANHA:
			if [[ "$machine" = "Mac" ]]; then
				echo "x" > ~/bin/piranha ; # overwrites existing file, if present
				sed -i.bak 's/x/bash\ \/Users\/justinbagley\/Downloads\/piranha\-master\/piranha\ $\*/g' ~/bin/piranha ;
				rm ~/bin/piranha.bak ;
				chmod u+x ~/bin/piranha ;
				echo "source \"\/Users\/justinbagley\/Downloads\/piranha\-master\/completions\/init\.sh\"" >> ~/.bash_profile ;
				source ~/.bash_profile ;
			elif [[ "$machine" = "Linux" ]]; then
				echo "x" > ~/local/bin/piranha ; # overwrites existing file, if present
				sed -i 's/x/bash\ \~\/local\/opt\/piranha\-master\/piranha\ $\*/g' ~/local/bin/piranha ;
				chmod u+x ~/local/opt/piranha-master/piranha ;
				chmod u+x ~/local/bin/piranha ;
				echo "source \"\/Users\/justinbagley\/Downloads\/piranha\-master\/completions\/init\.sh\"" >> ~/.bashrc ;
				source ~/.bashrc ;
			fi

		else

			## CASE #2: USER MACHINE

			## INSTALL PIrANHA:
			echo "INFO      | $(date) | Installing PIrANHA on ${USER}'s ${machine}... "
			cd "$HOME";
				if [[ -s ./piranha-master/ ]]; then
					echo "INFO      | $(date) | Found piranha-master/ distribution in user home ($HOME)... "
				elif [[ ! -s ./piranha-master/ ]]; then
					echo "INFO      | $(date) | Downloading piranha-master/ distribution to user home ($HOME)... "
					git clone https://github.com/justincbagley/piranha.git ./piranha-master/  ;
					cd ./piranha-master/bin/  ;
						echo "INFO      | $(date) | Granting execution permissions... "
						chmod u+x ./* ;
						chmod u+x ../piranha ;
						chmod u+x ../completions/init.sh ;
					cd ..;
				fi

			## SET UP PIrANHA:
			if [[ "$machine" = "Mac" ]]; then
				echo "INFO      | $(date) | Creating piranha executable... "
				echo "x" > ~/bin/piranha ; # overwrites existing file, if present
				sed -i.bak 's/x/bash\ \~\/piranha\-master\/piranha\ $\*/g' ~/bin/piranha ;
				rm ~/bin/piranha.bak ;
				chmod u+x ~/bin/piranha ;
				echo "source \""$HOME"\/piranha\-master\/completions\/init\.sh\"" >> ~/.bash_profile ;
				source ~/.bash_profile ;
			elif [[ "$machine" = "Linux" ]]; then
				echo "INFO      | $(date) | Creating piranha executable... "
				echo "x" > ~/bin/piranha ; # overwrites existing file, if present
				sed -i.bak 's/x/bash\ \~\/piranha\-master\/piranha\ $\*/g' ~/bin/piranha ;
				chmod u+x ~/bin/piranha ;
				echo "source \""$HOME"\/piranha\-master\/completions\/init\.sh\"" >> ~/.bashrc ;
				source ~/.bashrc ;
			fi

		fi
		###

echo "INFO      | $(date) | Done. 
"
##########################################################################################
######################################### END ############################################

}

local_piranha

exit 0

